modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Gustavaopere/Black-Arcana/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Gustavaopere/Black-Arcana"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="irons_spellbooks"
type="optional"
ordering="AFTER"
side="BOTH"
reason="Optional Black Arcana spell-host and mana integration"

[[dependencies.${mod_id}]]
modId="ars_nouveau"
type="optional"
ordering="AFTER"
side="BOTH"
reason="Optional Black Arcana mana and utility integration"

[[dependencies.${mod_id}]]
modId="eidolon_repraised"
type="optional"
ordering="AFTER"
side="BOTH"
reason="Optional Black Arcana ritual-host integration"

[[dependencies.${mod_id}]]
modId="malum"
type="optional"
ordering="AFTER"
side="BOTH"
reason="Optional Black Arcana spirit-resource integration"

[[dependencies.${mod_id}]]
modId="rpgskilltree"
type="optional"
ordering="AFTER"
side="BOTH"
reason="Optional Black Arcana progression and mastery integration"
